import subprocess
from pathlib import Path
from urllib.parse import parse_qs, urlparse

import httpx


class DouyinDownloader:
    LOGIN_COOKIE_NAMES = {"sessionid", "sid_guard", "passport_csrf_token", "odin_tt", "sid_tt", "uid_tt"}
    REQUIRED_WEB_COOKIE_NAMES = {"s_v_web_id"}

    def __init__(self, storage_dir: Path, cookies_path: str | None = None):
        self.storage_dir = storage_dir
        self.cookies_path = Path(cookies_path) if cookies_path else None
        self.raw_dir = storage_dir / "raw"
        self.raw_dir.mkdir(parents=True, exist_ok=True)

    async def resolve_url(self, url: str) -> str:
        try:
            async with httpx.AsyncClient(follow_redirects=True, timeout=20) as client:
                response = await client.get(url, headers={"User-Agent": "Mozilla/5.0"})
                return str(response.url)
        except httpx.HTTPError:
            return url

    async def download(self, video_id: int, url: str) -> tuple[Path | None, dict]:
        normalized_url = self.normalize_url(url)
        resolved_url = await self.resolve_url(normalized_url)
        resolved_url = self.normalize_url(resolved_url)
        output_template = str(self.raw_dir / f"{video_id}.%(ext)s")
        command = [
            "yt-dlp",
            "--no-playlist",
            "--socket-timeout",
            "30",
            "--user-agent",
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36",
            "--referer",
            "https://www.douyin.com/",
            "--merge-output-format",
            "mp4",
            "-o",
            output_template,
            resolved_url,
        ]
        if self.cookies_path and self.cookies_path.exists():
            sanitized_cookies_path = self.sanitize_cookies()
            command[1:1] = ["--cookies", str(sanitized_cookies_path)]
            cookie_warning = self.validate_cookies()
            if cookie_warning:
                return None, {"resolved_url": resolved_url, "warning": cookie_warning}
        elif self.cookies_path:
            return None, {
                "resolved_url": resolved_url,
                "warning": f"Douyin cookies file not found: {self.cookies_path}",
            }

        try:
            subprocess.run(command, check=True, capture_output=True, text=True, timeout=180)
        except FileNotFoundError:
            return None, {"resolved_url": resolved_url, "warning": "yt-dlp is not installed"}
        except subprocess.CalledProcessError as exc:
            return None, {"resolved_url": resolved_url, "warning": exc.stderr[-1000:]}

        candidates = sorted(self.raw_dir.glob(f"{video_id}.*"))
        return (candidates[0] if candidates else None), {"resolved_url": resolved_url}

    def normalize_url(self, url: str) -> str:
        parsed = urlparse(url)
        query = parse_qs(parsed.query)
        modal_id = query.get("modal_id", [None])[0]
        if modal_id and modal_id.isdigit():
            return f"https://www.douyin.com/video/{modal_id}"
        return url

    def validate_cookies(self) -> str | None:
        if not self.cookies_path or not self.cookies_path.exists():
            return None
        names: set[str] = set()
        try:
            for parts in self.iter_cookie_parts(self.cookies_path):
                if "douyin.com" in parts[0]:
                    names.add(parts[5])
        except OSError as exc:
            return f"Cannot read Douyin cookies file: {exc}"

        if not names:
            return "Douyin cookies file is empty or not in Netscape cookies.txt format."
        if not (names & self.LOGIN_COOKIE_NAMES):
            return (
                "Douyin cookies are not logged-in browser cookies. Export fresh cookies after logging in to douyin.com. "
                "Expected one of: sessionid, sid_guard, passport_csrf_token, odin_tt."
            )
        missing_web_cookies = self.REQUIRED_WEB_COOKIE_NAMES - names
        if missing_web_cookies:
            return (
                "Douyin logged-in cookies were found, but required web verification cookies are missing: "
                f"{', '.join(sorted(missing_web_cookies))}. Open the target video in the browser, wait for it to play, "
                "then export cookies again for all douyin.com domains."
            )
        return None

    def sanitize_cookies(self) -> Path:
        if not self.cookies_path:
            raise RuntimeError("Douyin cookies path is not configured.")

        output_path = self.cookies_path.with_suffix(".sanitized.txt")
        lines = [
            "# Netscape HTTP Cookie File",
            "# Generated by Tool_Tiktok from douyin_cookies.txt",
            "",
        ]
        for parts in self.iter_cookie_parts(self.cookies_path):
            lines.append("\t".join(parts))
        output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return output_path

    def iter_cookie_parts(self, path: Path) -> list[list[str]]:
        cookie_parts: list[list[str]] = []
        for raw_line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
            if not raw_line:
                continue
            line = raw_line
            if line.startswith("#HttpOnly_"):
                line = line.removeprefix("#HttpOnly_")
            elif line.startswith("#"):
                continue

            parts = [part.strip() for part in line.split("\t")]
            if len(parts) < 7:
                continue

            domain, include_subdomains, path_value, secure, expires, name = parts[:6]
            value = "\t".join(parts[6:])
            include_subdomains = include_subdomains.upper()
            secure = secure.upper()

            if include_subdomains not in {"TRUE", "FALSE"} or secure not in {"TRUE", "FALSE"}:
                continue
            if domain.startswith(".") and include_subdomains != "TRUE":
                include_subdomains = "TRUE"
            if not domain.startswith(".") and include_subdomains != "FALSE":
                include_subdomains = "FALSE"

            cookie_parts.append([domain, include_subdomains, path_value or "/", secure, expires or "0", name, value])
        return cookie_parts
